name: Publish to NPM

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
          registry-url: https://registry.npmjs.org
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - run: npm install
      - run: npm exec prettier -- --check '**/*.{js,ts}'
      - run: npm exec tslint -- '**/*.ts'
      - run: npm run build
      - name: Build diagascode
        run: |
          mkdir out/
          GOOS=linux go build -v -o out/diagascode-linux-amd64 .
          GOOS=windows go build -v -o out/diagascode-windows-amd64 .
          GOOS=darwin go build -v -o out/diagascode-macos-amd64 .
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: tip
          title: Development build
          prerelease: true
          files: out/*
